In [5]:
!pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ------------------------- -------------- 8.1/12.9 MB 41.8 MB/s eta 0:00:01
   ------------------------------------ --- 11.8/12.9 MB 29.5 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 21.9 MB/s eta 0:00:00


In [9]:
import numpy as np

arr = np.arange(5, 11)
print(arr)

[ 5  6  7  8  9 10]


In [16]:
import numpy as np

# Example array
arr = np.array([[2, 3, 2], [1, 2, 4], [5, 6, 7]])
print("Array:\n", arr)

# Count even numbers
even_count = np.sum(arr % 2 == 0)
print("Even numbers count:", even_count)


Array:
 [[2 3 2]
 [1 2 4]
 [5 6 7]]
Even numbers count: 5


In [11]:
import numpy as np

# Create a 5x4 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(5, 4))
print("2D Array:\n", arr)

col_mean = np.mean(arr, axis=0)
print("\nColumn-wise mean:", col_mean)

std_dev = np.std(arr)
print("Overall standard deviation:", std_dev)


2D Array:
 [[60  7 22 66]
 [ 2 24 17 36]
 [ 7 90 78 20]
 [60 95 90 78]
 [60 47 23 22]]

Column-wise mean: [37.8 52.6 46.  44.4]
Overall standard deviation: 30.047628858197783


In [13]:
!pip install pandas

   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ------------------------------- -------- 9.2/11.6 MB 52.1 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.6 MB 52.1 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.6 MB 21.9 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 18.2 MB/s eta 0:00:00

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]


In [15]:
import pandas as pd

# Given data
data = {
    'name': ['Alice', 'Bob', 'Jefin', 'David', 'Jude'],
    'math_score': [80, 64, 90, 72, 56],
    'english_score': [78, 85, 88, 69, 60]
}

df = pd.DataFrame(data)

df.rename(columns={'name': 'student_name'}, inplace=True)

df['average'] = ((df['math_score'] + df['english_score']) / 2).astype('int8')

df.drop(columns=['math_score', 'english_score'], inplace=True)

# print final DataFrame
print(df)


  student_name  average
0        Alice       79
1          Bob       74
2        Jefin       89
3        David       70
4         Jude       58


In [19]:
import pandas as pd

# Create the first DataFrame
data1 = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [24, 30, 22],
    'city': ['New York', 'Los Angeles', 'Chicago']
}

df1 = pd.DataFrame(data1)

# Create the second DataFrame
data2 = {
    'name': ['David', 'Eve', 'Frank'],
    'age': [28, 26, 35],
    'city': ['Houston', 'Phoenix', 'San Francisco']
}

df2 = pd.DataFrame(data2)

df_combined = pd.concat([df1, df2], ignore_index=True)

df_combined.reset_index(drop=True, inplace=True)

# print final DataFrame
print(df_combined)


      name  age           city
0    Alice   24       New York
1      Bob   30    Los Angeles
2  Charlie   22        Chicago
3    David   28        Houston
4      Eve   26        Phoenix
5    Frank   35  San Francisco


In [20]:
import pandas as pd

# Initialize the DataFrame with columns 'Name' and 'Age' and indices 1, 2, 3
student_info = pd.DataFrame(columns=['Name', 'Age'], index=[1, 2, 3])

# Populate the DataFrame using .loc
student_info.loc[1] = ['Alice', 24]
student_info.loc[2] = ['Bob', 30]
student_info.loc[3] = ['Charlie', 22]

student_info_sorted = student_info.sort_values(by='Age', ascending=False)

top_students = student_info_sorted.iloc[:2]['Name']
print(top_students)


2      Bob
1    Alice
Name: Name, dtype: object


In [21]:
import pandas as pd

# Initialize the DataFrame with given data and custom indices
data = {
    'item': ['apple', 'banana', 'cherry', 'dates'],
    'stock': [50, 20, 0, 30],
    'price': [50, 20, 100, 150]
}

df = pd.DataFrame(data, index=['A', 'B', 'C', 'D'])

# 1) Using .loc to set the stock of 'cherry' (index "C") to 10
df.loc['C', 'stock'] = 10
print("Updated DataFrame after setting 'cherry' stock to 10:\n", df)

# 2) Using .iloc to retrieve the price value at row position 1, column position 2
price_value = df.iloc[1, 2]
print("\nPrice value at row position 1, column position 2:", price_value)


Updated DataFrame after setting 'cherry' stock to 10:
      item  stock  price
A   apple     50     50
B  banana     20     20
C  cherry     10    100
D   dates     30    150

Price value at row position 1, column position 2: 20
