In [1]:
import numpy as np
import pandas as pd

In [3]:
array = np.arange(5,11)
print(array)

[ 5  6  7  8  9 10]


In [4]:
array = np.random.randint(1, 11, (3,3))
print("array: ", array)
even_count = np.count_nonzero(array%2 == 0)
print(even_count)

array:  [[ 2  4  3]
 [ 3 10  8]
 [ 8  2  2]]
7


In [5]:
array = np.random.randint(10, 131, (5,4))
print("array: ", array)
print("column mean : ",np.mean(array, axis=0))
print("Std :", np.std(array))

array:  [[106  57  47  62]
 [ 52  88 130  57]
 [123  67 103 122]
 [ 89  24  16 100]
 [ 57 106  18  51]]
column mean :  [85.4 68.4 62.8 78.4]
Std : 34.371317984622


In [10]:
data = {
  'name': ['Alice', 'Bob', 'Jefin', 'David', 'Jude'],
  'math_score': [80, 64, 90, 72, 56],
  'english_score': [78, 85, 88, 69, 60]
}
df = pd.DataFrame(data)
df['average'] = ((df['math_score'] + df['english_score']) / 2)
df.drop(['math_score', 'english_score'], axis=1, inplace=True)
print(df)

    name  average
0  Alice     79.0
1    Bob     74.5
2  Jefin     89.0
3  David     70.5
4   Jude     58.0


In [12]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob'],
    'age': [25, 30]
})
df2 = pd.DataFrame({
    'name': ['Charlie', 'David'],
    'age': [22, 28]
})
combined_df = pd.concat([df1, df2], axis=0)
combined_df.reset_index(drop=True, inplace=True)
print(combined_df)

      name  age
0    Alice   25
1      Bob   30
2  Charlie   22
3    David   28


In [6]:
df = pd.DataFrame(columns=['Name', 'Age'], index=[1, 2, 3])
df.index.name = 'Student Info'
df.loc[1] = ['Alice', 20]
df.loc[2] = ['Bob', 22]
df.loc[3] = ['Charlie', 21]
df_sorted = df.sort_values(by='Age', ascending=False)
top_two_names = df_sorted.iloc[:2]
print(top_two_names)

                 Name Age
Student Info             
2                 Bob  22
3             Charlie  21


In [5]:
department = {
  'dept_id': [10, 20, 30, 40],
  'dept_name': ['HR', 'IT', 'Sales', 'Finance']
}
employees = {
  'emp_id': [1, 2, 3, 4, 5],
  'name': ['Alice','Bob','Revin','David','Devin'],
  'dept_id': [20, 10, 30, 50, 20],
  'salary': [70000, 48000, 55000, 62000, 72000]
}
df_dept = pd.DataFrame(department)
df_emp = pd.DataFrame(employees)
result1 = pd.merge(df_emp, df_dept, on='dept_id', how='inner')
print(result1[['name', 'dept_name']])
result2 = pd.merge(df_emp, df_dept, on='dept_id', how='left')
print(result2[['name', 'dept_name']])

    name dept_name
0  Alice        IT
1    Bob        HR
2  Revin     Sales
3  Devin        IT
    name dept_name
0  Alice        IT
1    Bob        HR
2  Revin     Sales
3  David       NaN
4  Devin        IT


In [7]:
data = {
  'item':  ['apple', 'banana', 'cherry', 'dates'],
  'stock': [50, 20, 0, 30],
  'price': [50, 20, 100, 150]
}
df = pd.DataFrame(data, index=['A', 'B', 'C', 'D'])
df.loc['C', 'stock'] = 10
print(df)
value = df.iloc[1, 2]
print(value)

     item  stock  price
A   apple     50     50
B  banana     20     20
C  cherry     10    100
D   dates     30    150
20


In [8]:
data = {
  'first_name': ['John', 'Jane', 'Alice', 'Bob'],
  'last_name':  ['Doe',  'Smith','Johnson','Lee']
}
df = pd.DataFrame(data)
df['full_name'] = df['first_name'] + ' ' + df['last_name']
print(df)

  first_name last_name      full_name
0       John       Doe       John Doe
1       Jane     Smith     Jane Smith
2      Alice   Johnson  Alice Johnson
3        Bob       Lee        Bob Lee


In [11]:
data = {
  'order_id':  [101, 102, 103, 104, 105, 106, 107],
  'product_category': ['Electronics','Clothing','Electronics', 'Home','Clothing','Home','Electronics'],
  'order_value':  [250, 80, 120, 200, 50, 150, 300],
  'user_id': [1, 2, 1, 3, 2, 1, 2]
}
df = pd.DataFrame(data)
order_count = df['user_id'].value_counts().sort_index()
print(order_count)
avg_order_by_user = df.groupby('user_id')['order_value'].mean()
print(avg_order_by_user)
avg_order_by_category = df.groupby('product_category')['order_value'].mean()
print(avg_order_by_category)

user_id
1    3
2    3
3    1
Name: count, dtype: int64
user_id
1    173.333333
2    143.333333
3    200.000000
Name: order_value, dtype: float64
product_category
Clothing        65.000000
Electronics    223.333333
Home           175.000000
Name: order_value, dtype: float64
