In [1]:
# Create a 1D NumPy array of the integers 5 to 10.

import numpy as np

arr = np.arange(5, 11)
print(arr)

[ 5  6  7  8  9 10]


In [2]:
#Create a 2D numpy array with shape of (3, 3) & fill it with random numbers. Calculate the count of even numbers.

import numpy as np

arr = np.random.randint(0, 10, size=(3, 3))
print("Array:\n", arr)

even_count = np.sum(arr % 2 == 0)
print("Count of even numbers:", even_count)

Array:
 [[3 5 8]
 [1 9 3]
 [7 3 9]]
Count of even numbers: 1


In [3]:
# Create a 2D numpy array with shape (5,4) & fill with random numbers, calculate the mean(column wise) and the overall standard deviation:

import numpy as np

arr = np.random.randint(1, 10, size=(5, 4))
print("Array:")
print(arr)

col_means = np.mean(arr, axis=0)
print("Column-wise means:", col_means)

# Calculate overall standard deviation
overall_std = np.std(arr)
print("Overall standard deviation:", overall_std)

Array:
[[5 3 7 1]
 [3 2 8 1]
 [8 7 3 2]
 [5 2 9 9]
 [3 1 8 7]]
Column-wise means: [4.8 3.  7.  4. ]
Overall standard deviation: 2.830194339616981


In [4]:
import pandas as pd

data = {
    'name': ['Alice', 'Bob', 'Jefin', 'David', 'Jude'],
    'math_score': [80, 64, 90, 72, 56],
    'english_score': [78, 85, 88, 69, 60]
}

df = pd.DataFrame(data)

df = df.rename(columns={'name': 'student_name'})

df['average'] = ((df['math_score'] + df['english_score']) / 2).astype('int8')

df = df.drop(columns=['math_score', 'english_score'])

print(df)

print("\nDict version:")
print(df.to_dict('list'))


  student_name  average
0        Alice       79
1          Bob       74
2        Jefin       89
3        David       70
4         Jude       58

Dict version:
{'student_name': ['Alice', 'Bob', 'Jefin', 'David', 'Jude'], 'average': [79, 74, 89, 70, 58]}


In [8]:
import pandas as pd

# First DataFrame
df1 = pd.DataFrame({
    'student_name': ['Alice', 'Bob', 'Charlie'],
    'grade': ['A', 'B', 'A-'],
    'score': [95, 82, 88]
})

# Second DataFrame
df2 = pd.DataFrame({
    'student_name': ['David', 'Eva', 'Frank'],
    'grade': ['B+', 'A', 'C'],
    'score': [87, 92, 75]
})

combined_df = pd.concat([df1, df2], axis=0)

combined_df = combined_df.reset_index(drop=True)

print("First DataFrame:")
print(df1)
print("\nSecond DataFrame:")
print(df2)
print("\nCombined DataFrame:")
print(combined_df)

First DataFrame:
  student_name grade  score
0        Alice     A     95
1          Bob     B     82
2      Charlie    A-     88

Second DataFrame:
  student_name grade  score
0        David    B+     87
1          Eva     A     92
2        Frank     C     75

Combined DataFrame:
  student_name grade  score
0        Alice     A     95
1          Bob     B     82
2      Charlie    A-     88
3        David    B+     87
4          Eva     A     92
5        Frank     C     75


In [9]:
import pandas as pd

df = pd.DataFrame(columns=['Name', 'Age'], index=[1, 2, 3])
df.index.name = 'Student Info'

df.loc[1] = ['Alice', 20]
df.loc[2] = ['Bob', 22]
df.loc[3] = ['Charlie', 19]

# Sort by 'Age' in descending order
df_sorted = df.sort_values(by='Age', ascending=False)

# Display the top 2 students using .iloc
top_two_names = df_sorted.iloc[:2]['Name']

print("Original DataFrame:")
print(df)
print("\nSorted DataFrame (by Age, descending):")
print(df_sorted)
print("\nTop two students (oldest first):")
print(top_two_names)

Original DataFrame:
                 Name Age
Student Info             
1               Alice  20
2                 Bob  22
3             Charlie  19

Sorted DataFrame (by Age, descending):
                 Name Age
Student Info             
2                 Bob  22
1               Alice  20
3             Charlie  19

Top two students (oldest first):
Student Info
2      Bob
1    Alice
Name: Name, dtype: object


In [14]:
import pandas as pd

department = {
    'dept_id': [10, 20, 30, 40],
    'dept_name': ['HR', 'IT', 'Sales', 'Finance']
}

employees = {
    'emp_id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Revin', 'David', 'Devin'],
    'dept_id': [20, 10, 30, 50, 20],
    'salary': [70000, 48000, 55000, 62000, 72000]
}

dept_df = pd.DataFrame(department)
emp_df = pd.DataFrame(employees)

inner_merge = pd.merge(emp_df, dept_df, on='dept_id', how='inner')[['name', 'dept_name']]
print("Employee names with department (inner merge):")
print(inner_merge)

left_merge = pd.merge(emp_df, dept_df, on='dept_id', how='left')[['dept_name', 'name']]
print("\nAll employees with department (left merge):")
print(left_merge)

Employee names with department (inner merge):
    name dept_name
0  Alice        IT
1    Bob        HR
2  Revin     Sales
3  Devin        IT

All employees with department (left merge):
  dept_name   name
0        IT  Alice
1        HR    Bob
2     Sales  Revin
3       NaN  David
4        IT  Devin


In [16]:
import pandas as pd

data = {
    'item': ['apple', 'banana', 'cherry', 'dates'],
    'stock': [50, 20, 0, 30],
    'price': [50, 20, 100, 150]
}
df = pd.DataFrame(data, index=['A', 'B', 'C', 'D'])

print("Original DataFrame:")
print(df)

df.loc['C', 'stock'] = 10

print("\nAfter updating cherry stock:")
print(df)

price_value = df.iloc[1, 2]

print("\nPrice at row 1, column 2 (banana's price):", price_value)

Original DataFrame:
     item  stock  price
A   apple     50     50
B  banana     20     20
C  cherry      0    100
D   dates     30    150

After updating cherry stock:
     item  stock  price
A   apple     50     50
B  banana     20     20
C  cherry     10    100
D   dates     30    150

Price at row 1, column 2 (banana's price): 20


In [19]:
import pandas as pd

data = {
    'first_name': ['John', 'Jane', 'Alice', 'Bob'],
    'last_name': ['Doe', 'Smith', 'Johnson', 'Lee']
}
df = pd.DataFrame(data)

df['full_name'] = df['first_name'] + ' ' + df['last_name']

print(df)

  first_name last_name      full_name
0       John       Doe       John Doe
1       Jane     Smith     Jane Smith
2      Alice   Johnson  Alice Johnson
3        Bob       Lee        Bob Lee


In [20]:
import pandas as pd

data = {
    'order_id':  [101, 102, 103, 104, 105, 106, 107],
    'product_category':['Electronics','Clothing','Electronics', 'Home','Clothing','Home','Electronics'],
    'order_value':  [250, 80, 120, 200, 50, 150, 300],
    'user_id':[1, 2,  1, 3, 2, 1, 2]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# 1) Calculate count of order made by each user
orders_per_user = df.groupby('user_id')['order_id'].count()
print("\n1) Count of orders made by each user:")
print(orders_per_user)

# 2) Average of order_value by each user
avg_order_value_per_user = df.groupby('user_id')['order_value'].mean()
print("\n2) Average order_value by each user:")
print(avg_order_value_per_user)

# 3) Average order_value for each product_category
avg_order_value_per_category = df.groupby('product_category')['order_value'].mean()
print("\n3) Average order_value for each product_category:")
print(avg_order_value_per_category)

Original DataFrame:
   order_id product_category  order_value  user_id
0       101      Electronics          250        1
1       102         Clothing           80        2
2       103      Electronics          120        1
3       104             Home          200        3
4       105         Clothing           50        2
5       106             Home          150        1
6       107      Electronics          300        2

1) Count of orders made by each user:
user_id
1    3
2    3
3    1
Name: order_id, dtype: int64

2) Average order_value by each user:
user_id
1    173.333333
2    143.333333
3    200.000000
Name: order_value, dtype: float64

3) Average order_value for each product_category:
product_category
Clothing        65.000000
Electronics    223.333333
Home           175.000000
Name: order_value, dtype: float64
