In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
arr_1D = np.arange(5,11)
arr_1D

array([ 5,  6,  7,  8,  9, 10])

In [5]:
arr_2D = np.random.randint(1,100,size=(3,3))
arr_2D

array([[91, 35, 20],
       [18, 26, 43],
       [79, 44, 69]])

In [6]:
even_count = np.sum(arr_2D % 2==0)
print(even_count)

4


In [7]:
arr_2D_5_4 = np.random.randint(1,10,size=(5,4))
arr_2D_5_4

array([[1, 8, 7, 1],
       [7, 7, 7, 9],
       [3, 9, 9, 7],
       [7, 6, 9, 4],
       [6, 6, 4, 7]])

In [8]:
print("Column Wise Mean: ", np.mean(arr_2D_5_4,axis=0))
print("Standard Deviation: " ,np.std(arr_2D_5_4))

Column Wise Mean:  [4.8 7.2 7.2 5.6]
Standard Deviation:  2.379075450674064


In [9]:
input_data = {
'name': ['Alice','Bob','Jefin','David','Jude'],
'math_score':[80, 64, 90, 72, 56],
'english_score': [78, 85, 88, 69, 60]
}
data = pd.DataFrame(input_data)
data

name  math_score  english_score
0  Alice          80             78
1    Bob          64             85
2  Jefin          90             88
3  David          72             69
4   Jude          56             60

In [10]:
data.rename(columns={'name':'student_name'},inplace=True)
data

student_name  math_score  english_score
0        Alice          80             78
1          Bob          64             85
2        Jefin          90             88
3        David          72             69
4         Jude          56             60

In [11]:
data['average']=data[['math_score','english_score']].mean(axis=1).astype(np.int8)
data

student_name  math_score  english_score  average
0        Alice          80             78       79
1          Bob          64             85       74
2        Jefin          90             88       89
3        David          72             69       70
4         Jude          56             60       58

In [12]:
data.drop(columns=['math_score','english_score'],inplace=True)
data

student_name  average
0        Alice       79
1          Bob       74
2        Jefin       89
3        David       70
4         Jude       58

In [13]:
input_data_1 = pd.DataFrame({
    'studentname': ['Jeevitha', 'Vinotha'],
    'studentid': [1001, 1002]
})

input_data_2 = pd.DataFrame({
    'studentname': ['Priya', 'Aarthi', 'Shakthi'],
    'studentid': [101, 102, 103]
})

In [ ]:
data2=pd.DataFrame(columns=['Name','Age'],index=[1,2,3])
data2

In [14]:
data_frame = pd.concat([input_data_1,input_data_2],ignore_index=True)
data_frame

studentname  studentid
0    Jeevitha       1001
1     Vinotha       1002
2       Priya        101
3      Aarthi        102
4     Shakthi        103

In [17]:


df_department= pd.DataFrame({
'dept_id':   [10, 20, 30, 40],
'dept_name': ['HR', 'IT', 'Sales', 'Finance']
})
df_employees=pd.DataFrame({
'emp_id': [1, 2, 3, 4, 5],
'name': ['Alice','Bob','Revin','David','Devin'],
'dept_id': [20, 10, 30, 50, 20],
'salary': [70000, 48000, 55000, 62000, 72000]
})

In [18]:
result = pd.merge(df_employees, df_department, on='dept_id', how='left')
print(result[['dept_name', 'name']])

  dept_name   name
0        IT  Alice
1        HR    Bob
2     Sales  Revin
3       NaN  David
4        IT  Devin


In [19]:
result1 = pd.merge(df_employees, df_department, on='dept_id', how='inner')
print(result1[['name', 'dept_name']])

    name dept_name
0  Alice        IT
1    Bob        HR
2  Revin     Sales
3  Devin        IT


In [21]:
data_stock = {
'item':  ['apple', 'banana', 'cherry', 'dates'],
'stock': [50, 20, 0, 30],
'price': [50, 20, 100, 150]
 }
data_stock_df = pd.DataFrame(data_stock,index=['A','B','C','D'])
data_stock_df

item  stock  price
A   apple     50     50
B  banana     20     20
C  cherry      0    100
D   dates     30    150

In [22]:
data_stock_df.loc['C','stock'] = 10
data_stock_df

item  stock  price
A   apple     50     50
B  banana     20     20
C  cherry     10    100
D   dates     30    150

In [23]:
price_row1_colum2= data_stock_df.iloc[1,2]
print(price_row1_colum2)

20


In [24]:
names={
'first_name': ['John', 'Jane', 'Alice', 'Bob'],
'last_name':  ['Doe',  'Smith','Johnson','Lee']
}
names_df=pd.DataFrame(names)
names_df

first_name last_name
0       John       Doe
1       Jane     Smith
2      Alice   Johnson
3        Bob       Lee

In [25]:
names_df['full_name']=names_df['first_name']+ ' ' +names_df['last_name']
names_df

first_name last_name      full_name
0       John       Doe       John Doe
1       Jane     Smith     Jane Smith
2      Alice   Johnson  Alice Johnson
3        Bob       Lee        Bob Lee

In [26]:
orders={
'order_id':  [101, 102, 103, 104, 105, 106, 107],
'product_category':['Electronics','Clothing','Electronics', 'Home','Clothing','Home','Electronics'],
'order_value':  [250, 80, 120, 200, 50, 150, 300],
'user_id':[1, 2,  1, 3, 2, 1, 2]
}
orders_df=pd.DataFrame(orders)
orders_df

order_id product_category  order_value  user_id
0       101      Electronics          250        1
1       102         Clothing           80        2
2       103      Electronics          120        1
3       104             Home          200        3
4       105         Clothing           50        2
5       106             Home          150        1
6       107      Electronics          300        2

In [27]:
groupBy_user = orders_df.groupby('user_id')

In [28]:
order_count=groupBy_user['order_id'].count().reset_index(name='order_count')
average_order_value = groupBy_user['order_value'].mean().reset_index(name='order_mean')
order_count,average_order_value

(   user_id  order_count
 0        1            3
 1        2            3
 2        3            1,
    user_id  order_mean
 0        1  173.333333
 1        2  143.333333
 2        3  200.000000)

In [29]:
groupBy_product = orders_df.groupby('product_category')
average_order_value_product =  groupBy_product['order_value'].mean().reset_index(name='order_avg_product')
average_order_value_product

product_category  order_avg_product
0         Clothing          65.000000
1      Electronics         223.333333
2             Home         175.000000