1.Write a Python program to count the number of characters in a string.,
,Sample String : 'google.com'
,"Expected Result : {'o': 3, 'g': 2, '.': 1, 'e': 1, 'l': 1, 'm': 1, 'c': 1}"

In [ ]:
str = "google.com"

dict = {}
for n in str:
  keys = dict.keys()
  if n in keys:
    dict[n] += 1
  else:
    dict[n] = 1
print(dict)

{'g': 2, 'o': 3, 'l': 1, 'e': 1, '.': 1, 'c': 1, 'm': 1}


2. Write a Python program to count the number of strings where the string length is 2 or more and the first and last character are same from a given list of strings.,
,"Sample List : ['abc', 'xyz', 'aba', '1221']"

In [ ]:
list = ['abc', 'xyz', 'aba', '1221']
count = 0
for n in list:
  if len(n) >= 2 and n[0] == n[-1]:
    count += 1
print(count)

2


3. Write a Python program to get a string made of the first 2 and the last 2 chars from a given a string. If the string length is less than 2, return instead the empty string


In [ ]:
def string_ends(str):
  if len(str)<2:
    return ""
  return str[:2]+str[-2:]

print(string_ends('w3resource'))
print(string_ends('w3'))
print(string_ends('w'))

w3ce
w3w3



4 .Write a Python program to get a list, sorted in increasing order by the last element in each tuple from a given list of non-empty tuples. Go to the editor",
,"Sample List : [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]"
,"Expected Result : [(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]"

In [ ]:
def sort_list_last(tuples):
  return sorted(tuples, key=lambda x: x[-1])

print(sort_list_last([(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]))

[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]


5. Write a Python program to add 'ing' at the end of a given string (length should be at least 3). If the given string is already ends with 'ing' then add 'ly' instead. If the string length of the given string is less than 3, leave it unchanged


In [ ]:
def add_string(str1):
  length = len(str1)

  if length > 2:
    if str1[-3:] == 'ing':
      str1 += 'ly'
    else:
      str1 += 'ing'

  return str1

In [ ]:
# prompt: 6. Create a list comprehension that generates a list of squares of numbers from 1 to 20.,

squares = [x**2 for x in range(1,21)]
squares


[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400]

In [ ]:
#7. Given a list of integers, find the largest and smallest numbers in the list without using the built-in max() and min() functions."

def find_largest_smallest(numbers):
    if not numbers:
        return None, None  # Handle empty list case

    largest = numbers[0]
    smallest = numbers[0]

    for n in numbers:
        if n > largest:
            largest = n
        elif n < smallest:
            smallest = n

    return largest, smallest

# Example usage
numbers = [-3, -1, 4, 1, 5, 9, 2, 6]
largest, smallest = find_largest_smallest(numbers)
print(f"Largest: {largest}, Smallest: {smallest}")

Largest: 9, Smallest: -3


In [ ]:
# 8. Write a function that takes two lists and returns a set of elements that are common to both lists.,

def common_elements(list1, list2):
  """
  This function takes two lists and returns a set of elements that are common to both lists.
  """
  return set(list1) & set(list2)

common_elements([1, 2, 3, 4, 5], [4, 5, 6, 7, 8])


{4, 5}

In [ ]:
# 9. Given a list of words, return a set of words that appear more than once in the list.

def find_duplicate_words(word_list):

    word_counts = {}
    duplicates = set()

    for word in word_list:
        if word in word_counts:
            word_counts[word] += 1
            duplicates.add(word)
        else:
            word_counts[word] = 1

    return duplicates

find_duplicate_words(["apple", "banana", "cherry", "banana", "date", "apple"])


{'apple', 'banana'}

In [ ]:
# 10. Given two sets, write a function to return their union, intersection, and difference.

def set_operations(set1, set2):
  """
  This function takes two sets and returns their union, intersection, and difference.
  """
  union_set = set1.union(set2)
  intersection_set = set1.intersection(set2)
  difference_set = set1.difference(set2)
  return union_set, intersection_set, difference_set

# Example usage
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
union, intersection, difference = set_operations(set1, set2)
print(f"Union: {union}")
print(f"Intersection: {intersection}")
print(f"Difference (set1 - set2): {difference}")


Union: {1, 2, 3, 4, 5, 6, 7, 8}
Intersection: {4, 5}
Difference (set1 - set2): {1, 2, 3}


In [ ]:
# 11. Given a list of tuples where each tuple contains a name and a score (e.g., [('Alice', 90), ('Bob', 85), ('Alice', 95)]), write a function to return a dictionary where each name maps to the sum of their scores.

def sum_scores(scores):
  """
  This function takes a list of tuples (name, score) and returns a dictionary
  mapping each name to the sum of their scores.
  """
  name_scores = {}
  for name, score in scores:
    name_scores[name] = name_scores.get(name, 0) + score
  return name_scores

# Example usage
scores = [('Alice', 90), ('Bob', 85), ('Alice', 95)]
result = sum_scores(scores)
print(result)  # Output: {'Alice': 185, 'Bob': 85}


{'Alice': 185, 'Bob': 85}


In [ ]:
# 12. Create a dictionary comprehension that maps each word in a list to its length.

words = ["apple", "banana", "cherry"]
word_lengths = {word: len(word) for word in words}
word_lengths


{'apple': 5, 'banana': 6, 'cherry': 6}

In [ ]:
# 13. Write a function that takes a tuple of numbers and returns a new tuple with each element doubled,

def double_tuple(numbers):
    return tuple(x * 2 for x in numbers)

double_tuple((0, 1, -2, -3, 4, 5))


(0, 2, -4, -6, 8, 10)

In [ ]:
# 14. Write a function that swaps the first and last elements of a tuple.,

def swap_first_last(input_tuple):
    if len(input_tuple) < 2:
        return input_tuple
    else:
        return input_tuple[-1:] + input_tuple[1:-1] + input_tuple[:1]

swap_first_last((1, 2, 3, 4, 5))


(5, 2, 3, 4, 1)

In [ ]:
# 15. Write a function that takes two tuples and returns a new tuple that contains all elements from both tuples without any duplicates.,

def combine_tuples(tuple1, tuple2):
    return tuple(set(tuple1 + tuple2))

combine_tuples((1, 2, 3), (3, 4, 5))




(1, 2, 3, 4, 5)

In [ ]:
# 16. Write a program to find the factorial of a number using a while loop.,

def factorial(n):
    if n < 0:
        return "Factorial is not defined for negative numbers"
    elif n == 0:
        return 1
    else:
        fact = 1
        i = 1
        while i <= n:
            fact *= i
            i += 1
        return fact

# Example usage
number = 5
result = factorial(number)
print(f"The factorial of {number} is {result}")


The factorial of 5 is 120


In [ ]:
# 17. Write a program that finds the sum of all even numbers from 1 to 100 using a for loop.
sum_of_evens = 0
for i in range(2, 101, 2):
    sum_of_evens += i
print(f"The sum of all even numbers from 1 to 100 is: {sum_of_evens}")


The sum of all even numbers from 1 to 100 is: 2550


In [ ]:
# 18. Write a program to count the number of vowels in a string using membership operators (in),

def count_vowels(input_string):
    vowels = "aeiouAEIOU"
    vowel_count = 0
    for char in input_string:
        if char in vowels:
            vowel_count += 1
    return vowel_count

count_vowels("Hello, World!")


3

In [ ]:
# 19. Write a program that takes a number and determines if it's even or odd using the modulus operator %,

def check_even_odd(number):
    if number % 2 == 0:
        return "Even"
    else:
        return "Odd"

# Example usage
number = 10
result = check_even_odd(number)
print(f"The number {number} is {result}")

number = 7
result = check_even_odd(number)
print(f"The number {number} is {result}")


The number 10 is Even
The number 7 is Odd


In [ ]:
# 20. Write a program to check whether a person can vote (age >= 18) using logical operators,

def check_vote_eligibility(age):
    return age >= 18

# Example usage
age = 20
if check_vote_eligibility(age):
    print("This person can vote.")
else:
    print("This person cannot vote.")

age = 15
if check_vote_eligibility(age):
    print("This person can vote.")
else:
    print("This person cannot vote.")


This person can vote.
This person cannot vote.


In [ ]:
# 21. Write a program to yield positive number from the given listing using python generator,"nums = [-3, -2, 0, 1, 2, 4, 5, 7]"

def positive_numbers(nums):
    for num in nums:
        if num > 0:
            yield num

nums = [-3, -2, 0, 1, 2, 4, 5, 7]
for num in positive_numbers(nums):
  print(num)


1
2
4
5
7


In [ ]:
# 22. Write a function name 'welcome' that prints a welcome message for the user using default argument,if user name provided that shoult print user name, otherwise default name should be printed

def welcome(user_name="Guest"):
  print(f"Welcome, {user_name}!")

welcome("Python")


Welcome, Python!


In [ ]:
#23. Write a function sum_all(*args) that accepts any number of numeric arguments and returns their sum.,"sum_all(1, 2, 3)"

def sum_all(*args):

  total = 0
  for num in args:
    total += num
  return total

sum_all(1, 2, 3)

6

In [ ]:
# 24. Write a function print_user_info(**kwargs) that accepts any number of keyword arguments and prints them in key: value format.,"print_user_info(name=""Alice"", age=25, city=""NYC"")"

def print_user_info(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

print_user_info(name="Alice", age=25, city="NYC")


name: Alice
age: 25
city: NYC


In [135]:
# 25. Scopes - local & global:You have a global variable visits initialized to 0.Write a function track_visit(page) that:Increments the global visits by 1 each time it’s called.Creates a local variable called message like: ""User visited {page}. Total visits: {visits}""Prints the message.","Expected Behavior:visits = 0
# track_visit(""Home"")     # ➞ User visited Home. Total visits: 1
# track_visit(""About"")    # ➞ User visited About. Total visits: 2
# print(visits)           # ➞ 2

visits = 0

def track_visit(page):
    global visits
    visits += 1
    message = f"User visited {page}. Total visits: {visits}"
    print(message)

track_visit("Home")     # ➞ User visited Home. Total visits: 1
track_visit("About")    # ➞ User visited About. Total visits: 2
print(visits)           # ➞ 2


User visited Home. Total visits: 1
User visited About. Total visits: 2
2


## **Python OOPS Hands on**


In [193]:
# 26. Builtin functions
# You are given two lists:
# A list of student names
# A list of scores they received in a test.
# names = ["Alice", "Bob", "Charlie", "Diana", "Eve"]
# scores = [85, 42, 73, 60, 29]
# Using Python, do the following:
# -----------------------------------------
from functools import reduce

names = ["Alice", "Bob", "Charlie", "Diana", "Eve"]
scores = [85, 42, 73, 60, 29]


# 1. Pair names with scores
zippedPair = list(zip(names, scores))
print("Zipped pair:",zippedPair)

# 2. Use map() to convert the scores into letter grades:
def get_grade(score):
    if score >= 85:
        return 'A'
    elif score >= 70:
        return 'B'
    elif score >= 50:
        return 'C'
    else:
        return 'F'

print("Grades:" , list(map(get_grade, scores)))

# 3.Use filter() to get only the students who passed (score ≥ 50).
print("Passing students:",list(filter(lambda x: x[1] >= 50, zippedPair)))

# 4.Use reduce() to calculate the total score.
print("Total score:",reduce(lambda x, y: x + y, scores))

# 5. Enumerate students
for index, name in enumerate(names,11):
    print(f"{index}. {name}")

# 6. Print type of paired data
print(type(zippedPair))

# # 7. Print memory address of scores list
print(id(scores))

# # 8. Generate and print ranks
sorted_name = sorted(zippedPair, key=lambda x: x[1], reverse=True)
for rank,(name,score) in enumerate(sorted_name,1):
  print(f"{rank}. {name} - {score}")


Zipped pair: [('Alice', 85), ('Bob', 42), ('Charlie', 73), ('Diana', 60), ('Eve', 29)]
Grades: ['A', 'F', 'B', 'C', 'F']
Passing students: [('Alice', 85), ('Charlie', 73), ('Diana', 60)]
Total score: 289
11. Alice
12. Bob
13. Charlie
14. Diana
15. Eve
<class 'list'>
137403318625664
1. Alice - 85
2. Charlie - 73
3. Diana - 60
4. Bob - 42
5. Eve - 29


In [239]:
# 27. Create a class Vehicle:
# -Public attribute: model
# -Protected attribute: max_speed
# -Private attribute: vehicle_id (auto-incremented)
# -Instance method display_info() to show vehicle info
# -Class method get_vehicle_count() to return total vehicles
# -Static method is_speeding(speed) → return True if speed > 100
# -Class variable for vehicle count
# -Create a subclass Truck:
#    -Adds cargo_capacity attribute
#    -Overrides display_info() to include cargo capacity

class Vehicle:
    vehicle_count = 0

    def __init__(self, model, max_speed):
        self.model = model
        self._max_speed = max_speed
        self.__vehicle_id = Vehicle.vehicle_count
        Vehicle.vehicle_count += 1

    def display_info(self):
        print(f"Model: {self.model}, Max Speed: {self._max_speed}, Vehicle ID: {self.__vehicle_id}")

    @classmethod
    def get_vehicle_count(cls):
        return cls.vehicle_count

    @staticmethod
    def is_speeding(speed):
        return speed > 100


class Truck(Vehicle):
    def __init__(self, model, max_speed, cargo_capacity):
        super().__init__(model, max_speed)
        self.cargo_capacity = cargo_capacity

    def display_info(self):
        super().display_info()
        print(f"Cargo Capacity: {self.cargo_capacity}")


# Example usage
v1 = Vehicle("Sedan", 90)
v2 = Vehicle("Coupe", 120)
t1 = Truck("Volvo Truck", 85, 15)

v1.display_info()
print("---")
t1.display_info()
print("---")
print("Total vehicles:", v1.get_vehicle_count())
print("Is 110 speeding?", v1.is_speeding(110))

print(f"Total vehicles: {t1.get_vehicle_count()}")
print(f"Is truck speeding? {t1.is_speeding(t1._max_speed)}")


Model: Sedan, Max Speed: 90, Vehicle ID: 0
---
Model: Volvo Truck, Max Speed: 85, Vehicle ID: 2
Cargo Capacity: 15
---
Total vehicles: 3
Is 110 speeding? True
Total vehicles: 3
Is truck speeding? False


In [250]:
# 28. Decorator:
# Create a function called greet_user(name) that returns a string:
# "Hello, <name>!" (where <name> is the input parameter).
# Write a decorator called uppercase_decorator that modifies the function
# it decorates so that the returned string is converted to uppercase.


def uppercase_decorator(func):
  def wrapper(args):
    result = func(args)
    return result.upper()
  return wrapper

@uppercase_decorator
def greet_user(name):
  return(f"Hello, {name}!")

greet_user("Alice")


'HELLO, ALICE!'

## **NUMPY and Pandas HandsOn**



In [9]:
import numpy as np
np.arange(5,11)


array([ 5,  6,  7,  8,  9, 10])

In [27]:
import numpy as np

random_array = np.random.randint(0,100,size=(3,3))

even_count = 0
for n in random_array:
  for d in n:
    if(d%2==0):
      even_count=even_count+1


print("2D Array:\n", random_array)
print("Count of even numbers:", even_count)


2D Array:
 [[95 51 95]
 [ 3 93 22]
 [14 42 28]]
Count of even numbers: 4


In [57]:
np3 = np.random.randint(0,100,size=(5,4))


print(np3.mean(),"\n")

for n in np3:
  print(n.mean())

print("\n2D Array:\n", np3)

print("\nColumn-wise means:\n", np.mean(np3, axis=0))

print("\nOverall standard deviation:\n", np.std(np3))





50.65 

46.0
40.0
53.0
51.75
62.5

2D Array:
 [[15 71 75 23]
 [27  7 91 35]
 [89  7 57 59]
 [49 27 91 40]
 [99 63 26 62]]

Column-wise means:
 [55.8 35.  68.  43.8]

Overall standard deviation:
 28.632629987481067


In [74]:
import pandas as pd

data ={
    'name': ['Alice', 'Bob', 'Jefin', 'David', 'Jude'],
    'math_score': [80, 64, 90, 72, 56],
    'english_score': [78, 85, 88, 69, 60]
}

df = pd.DataFrame(data)

df = df.rename(columns={'name':'student_name'})

df['average'] = ((df.math_score+df.english_score)//2).astype(np.int8)

df = df.drop(['math_score','english_score'], axis=1)
print(df)


  student_name  average
0        Alice       79
1          Bob       74
2        Jefin       89
3        David       70
4         Jude       58


In [82]:
# Create the first DataFrame
data1 = {'col1': [1, 2, 3], 'col2': ['A', 'B', 'C']}
df1 = pd.DataFrame(data1)

# Create the second DataFrame
data2 = {'col1': [4, 5, 6], 'col2': ['D', 'E', 'F']}
df2 = pd.DataFrame(data2)

concatenated_df = pd.concat([df1,df2])

print("\nconcatenated_df:\n",concatenated_df)


concatenated_df:
    col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [92]:
df = pd.DataFrame(columns=['Name','Age'], index=[1,2,3])
df.loc[1] = ['Alice', 20]
df.loc[2] = ['Bob', 22]
df.loc[3] = ['Charlie', 19]

sorted_df = df.sort_values('Age',ascending=False)

print(sorted_df[:2]['Name'])


2      Bob
1    Alice
Name: Name, dtype: object


In [101]:
department = {
    'dept_id': [10, 20, 30, 40],
    'dept_name': ['HR', 'IT', 'Sales', 'Finance']
}
employees = {
    'emp_id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Revin', 'David', 'Devin'],
    'dept_id': [20, 10, 30, 50, 20],
    'salary': [70000, 48000, 55000, 62000, 72000]
}

# Create dataframes
df_dept = pd.DataFrame(department)
df_emp = pd.DataFrame(employees)

# 1) Skip employees with no matching department
merged_df1 = pd.merge(df_dept,df_emp)
print("\n",merged_df1[['name','dept_name']])

# 2) Include all employees, even without department data
merged_df2 = pd.merge(df_emp,df_dept,how='left')
print("\n",merged_df2[['dept_name','name']])



     name dept_name
0    Bob        HR
1  Alice        IT
2  Devin        IT
3  Revin     Sales

   dept_name   name
0        IT  Alice
1        HR    Bob
2     Sales  Revin
3       NaN  David
4        IT  Devin


In [117]:
data = {
    'item': ['apple', 'banana', 'cherry', 'dates'],
    'stock': [50, 20, 0, 30],
    'price': [500, 200, 100, 150]
}

df = pd.DataFrame(data, index=['A', 'B', 'C', 'D'])

# 1) Using loc, set the stock of cherry (index: "C") to 10
df.loc['C','stock'] = 10


# 2) Using iloc, retrieve the price value at row position 1, column position 2
price_at_1_2 = df.iloc[1, 2]

print(df)
print(f"\nPrice at row 1, column 2: {price_at_1_2}")



     item  stock  price
A   apple     50    500
B  banana     20    200
C  cherry     10    100
D   dates     30    150

Price at row 1, column 2: 200


In [120]:
data = {
    'first_name': ['John', 'Jane', 'Alice', 'Bob'],
    'last_name':  ['Doe',  'Smith','Johnson','Lee']
}

df = pd.DataFrame(data)
df['full_name'] = df['first_name'] + ' '  + df['last_name']
df

first_name last_name      full_name
0       John       Doe       John Doe
1       Jane     Smith     Jane Smith
2      Alice   Johnson  Alice Johnson
3        Bob       Lee        Bob Lee

In [134]:

data = {
    'order_id':  [101, 102, 103, 104, 105, 106, 107],
    'product_category':['Electronics','Clothing','Electronics', 'Home','Clothing','Home','Electronics'],
    'order_value':  [250, 80, 120, 200, 50, 150, 300],
    'user_id':[1, 2,  1, 3, 2, 1, 2]
}

df = pd.DataFrame(data)

print(df)

# 1. Count of orders made by each user
order_count = df.groupby('user_id')['order_id'].count()
print("Count of orders made by each user:\n", order_count)

# 2. Average order value by each user
average_order_value = df.groupby('user_id')['order_value'].mean()
print("\nAverage order value by each user:\n", average_order_value)


# 3. Average order value for each product category
average_order_value_category = df.groupby('product_category')['order_value'].mean()
print("\nAverage order value for each product category:\n", average_order_value_category)


   order_id product_category  order_value  user_id
0       101      Electronics          250        1
1       102         Clothing           80        2
2       103      Electronics          120        1
3       104             Home          200        3
4       105         Clothing           50        2
5       106             Home          150        1
6       107      Electronics          300        2
Count of orders made by each user:
 user_id
1    3
2    3
3    1
Name: order_id, dtype: int64

Average order value by each user:
 user_id
1    173.333333
2    143.333333
3    200.000000
Name: order_value, dtype: float64

Average order value for each product category:
 product_category
Clothing        65.000000
Electronics    223.333333
Home           175.000000
Name: order_value, dtype: float64
